baseurl = "http://colemanfitbitcompetitions.com/"
title = "Year of the Step"

# Copyright
copyright = "(c) 2016 Chase Coleman."

# Language
languageCode = "en-EN"

# Theme to use (located in /themes/THEMENAME/)
theme = "hyde-y"

# Pagination
paginate = 10
paginatePath = "page"

[permalinks]
    post = "/:year/:month/:day/:slug/"
    code = "/:slug/"

[taxonomies]
    tag = "tags"
    topic = "topics"

[author]
    name = "Coleman Fitbit Competition"
    email = "info@colemanfitbitcompetitions.com"

# All parameters below here are optional and can be mixed and matched.
[params]
    # You can use markdown here.
    brand = "Coleman Fitbit Competition"
    topline = "Year of the Step"
    footline = "This is not a sprint, it's a marathon"

    # Sidebar position
    # false, true, "left", "right"
    sidebar = false

    # Text for the top menu link, which goes the root URL for the site.
    # Default (if omitted) is "Home".
    home = "Home"

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "tomorrow"

    # Google Analytics.
    googleAnalytics = "UA-71861843-1"

[blackfriday]
    angledQuotes = true
    fractions = true
    hrefTargetBlank = false
    latexDashes = true
    plainIdAnchors = true
    extensions = []
    extensionmask = []